// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import CollapsePersistController from "./collapse_persist_controller"
application.register("collapse-persist", CollapsePersistController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GachaResultController from "./gacha_result_controller"
application.register("gacha-result", GachaResultController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalCloseHookController from "./modal_close_hook_controller"
application.register("modal-close-hook", ModalCloseHookController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import SushiCardController from "./sushi_card_controller"
application.register("sushi-card", SushiCardController)
